### ISSUE TITLE
minSdkVersion

### ISSUE THREAD

**Issue by mylhyl** [MFlisar/RxBus2#3]
minSdkVersion drop 15 ok?

**Comment by MFlisar** [comment]
I don't mind. I anyways always use a personal setup via defining my versions in my apps so that this https://github.com/MFlisar/RxBus2/blob/master/lib/build.gradle#L9 if is true...

**Comment by MFlisar** [comment]
I close this due to inactivity...

Will change the min sdk if I add new functions or someone else adds something
