### ISSUE TITLE
Fragment fragment communication

### ISSUE THREAD

**Issue by jcarlos79t** [MFlisar/RxBus2#5]
How can I send messages between fragment with the bus?

**Comment by MFlisar** [comment]
For example like following:

**Fragment**

	public class MyFragment extends BaseFragment {
	
		@Override
		public void onCreate(Bundle savedInstanceState) {
			super.onCreate(savedInstanceState);

			RxBusBuilder.create(Event.class)
					.withBound(this) // use this if you want the disposable to automatically unsubscribe via the call to RxDisposableManager.unsubscribe(this) in the BaseFragment
					.withQueuing(this) // use this to queue events if the fragment is paused, don't use this to always immediately get event
					.withMode(RxBusMode.Main) // use this to observe the event on the main thread
					.subscribe(event -> {
						// handle event
						
					});
		}	
	}

**BaseFragment**

	public abstract class BaseFragment extends Fragment implements IRxBusQueue {
		private final BehaviorProcessor<Boolean> pauser = BehaviorProcessor.createDefault(false);

		@Override
		public void onResume() {
			super.onResume();
			pauser.onNext(true);
		}

		@Override
		public void onPause() {
			pauser.onNext(false);
			super.onPause();
		}

		@Override
		public void onDestroy() {
			RxDisposableManager.unsubscribe(this);
			super.onDestroy();
		}

		// --------------
		// RXBus
		// --------------

		@Override
		public boolean isBusResumed() {
			return pauser.getValue();
		}

		@Override
		public Publisher<Boolean> getResumeObservable() {
			return pauser;
		}
	}


**Sending events from ANYWHERE**

	RxBus.get().send(new Event());
