### ISSUE TITLE
如何调用.bindToLifecycle

### ISSUE THREAD

**Issue by Danniel-yan** [MFlisar/RxBus2#6]
RxBusBuilder.create(CityEvent::class.java).build().bindToLifecycle(mActivity.findViewById(android.R.id.content)).subscribe {
        }
现在这么写bindToLifecycle报错，不知道如何解决。求指教

**Comment by MFlisar** [comment]
Sorry, but I need an english question, otherwise I can't help

**Comment by MFlisar** [comment]
will close this, please reopen an english issue if you still have issues
