### ISSUE TITLE
Can this library not be used in the service?

### ISSUE THREAD

**Issue by LeonLab** [MFlisar/RxBus2#8]
I was used RxBusBuilder to create a listener in service，but it can not receives event。

**Comment by MFlisar** [comment]
Does the service run in the same process as the app? Then it should work. Otherwise it won't.

There's no IPC or similar handling

**Comment by LeonLab** [comment]
Thank you，It is work. I made a mistake,I used create().withBound different string，but RxDisposableManager.unsubscribe(“any”) will unsubscribed  ALL subscriptions.I didn't fully understand this method before.

**Comment by LeonLab** [comment]
RxBusDefaults.get() is not public.
